/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author USER
 */
public class CalculatorApp extends javax.swing.JFrame {

    /**
     * Creates new form CalculatorApp
     */
    public CalculatorApp() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        done = new javax.swing.JButton();
        sub = new javax.swing.JButton();
        eight = new javax.swing.JButton();
        five = new javax.swing.JButton();
        nine = new javax.swing.JButton();
        seven = new javax.swing.JButton();
        four = new javax.swing.JButton();
        six = new javax.swing.JButton();
        dall = new javax.swing.JButton();
        one = new javax.swing.JButton();
        two = new javax.swing.JButton();
        three = new javax.swing.JButton();
        add = new javax.swing.JButton();
        twozero = new javax.swing.JButton();
        zero = new javax.swing.JButton();
        mul = new javax.swing.JButton();
        equal = new javax.swing.JButton();
        dot = new javax.swing.JButton();
        div = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(0, 217, 240));
        jPanel1.setPreferredSize(new java.awt.Dimension(60, 50));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setFont(new java.awt.Font("DialogInput", 1, 36)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        jLabel1.setOpaque(true);
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 270, 50));

        done.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        done.setText("X");
        done.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        done.setPreferredSize(new java.awt.Dimension(60, 50));
        done.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                doneActionPerformed(evt);
            }
        });
        jPanel1.add(done, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 80, 60, 40));

        sub.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        sub.setText("-");
        sub.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        sub.setPreferredSize(new java.awt.Dimension(60, 50));
        sub.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                subActionPerformed(evt);
            }
        });
        jPanel1.add(sub, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 230, 60, 40));

        eight.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        eight.setText("8");
        eight.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        eight.setPreferredSize(new java.awt.Dimension(60, 50));
        eight.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                eightActionPerformed(evt);
            }
        });
        jPanel1.add(eight, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 80, 60, 40));

        five.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        five.setText("5");
        five.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        five.setPreferredSize(new java.awt.Dimension(60, 50));
        five.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fiveActionPerformed(evt);
            }
        });
        jPanel1.add(five, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 130, 60, 40));

        nine.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        nine.setText("9");
        nine.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        nine.setPreferredSize(new java.awt.Dimension(60, 50));
        nine.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nineActionPerformed(evt);
            }
        });
        jPanel1.add(nine, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 80, 60, 40));

        seven.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        seven.setText("7");
        seven.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        seven.setPreferredSize(new java.awt.Dimension(60, 50));
        seven.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sevenActionPerformed(evt);
            }
        });
        jPanel1.add(seven, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 80, 60, 40));

        four.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        four.setText("4");
        four.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        four.setPreferredSize(new java.awt.Dimension(60, 50));
        four.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fourActionPerformed(evt);
            }
        });
        jPanel1.add(four, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 130, 60, 40));

        six.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        six.setText("6");
        six.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        six.setPreferredSize(new java.awt.Dimension(60, 50));
        six.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sixActionPerformed(evt);
            }
        });
        jPanel1.add(six, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 130, 60, 40));

        dall.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        dall.setText("CE");
        dall.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        dall.setPreferredSize(new java.awt.Dimension(60, 50));
        dall.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dallActionPerformed(evt);
            }
        });
        jPanel1.add(dall, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 130, 60, 40));

        one.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        one.setText("1");
        one.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        one.setPreferredSize(new java.awt.Dimension(60, 50));
        one.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                oneActionPerformed(evt);
            }
        });
        jPanel1.add(one, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 180, 60, 40));

        two.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        two.setText("2");
        two.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        two.setPreferredSize(new java.awt.Dimension(60, 50));
        two.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                twoActionPerformed(evt);
            }
        });
        jPanel1.add(two, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 180, 60, 40));

        three.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        three.setText("3");
        three.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        three.setPreferredSize(new java.awt.Dimension(60, 50));
        three.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                threeActionPerformed(evt);
            }
        });
        jPanel1.add(three, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 180, 60, 40));

        add.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        add.setText("+");
        add.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        add.setPreferredSize(new java.awt.Dimension(60, 50));
        add.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addActionPerformed(evt);
            }
        });
        jPanel1.add(add, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 180, 60, 40));

        twozero.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        twozero.setText("00");
        twozero.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        twozero.setPreferredSize(new java.awt.Dimension(60, 50));
        twozero.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                twozeroActionPerformed(evt);
            }
        });
        jPanel1.add(twozero, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 230, 60, 40));

        zero.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        zero.setText("0");
        zero.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        zero.setPreferredSize(new java.awt.Dimension(60, 50));
        zero.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                zeroActionPerformed(evt);
            }
        });
        jPanel1.add(zero, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 230, 60, 40));

        mul.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        mul.setText("*");
        mul.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        mul.setPreferredSize(new java.awt.Dimension(60, 50));
        mul.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mulActionPerformed(evt);
            }
        });
        jPanel1.add(mul, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 290, 60, 40));

        equal.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        equal.setText("=");
        equal.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        equal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                equalActionPerformed(evt);
            }
        });
        jPanel1.add(equal, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 290, 130, 40));

        dot.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        dot.setText(".");
        dot.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        dot.setPreferredSize(new java.awt.Dimension(60, 50));
        dot.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dotActionPerformed(evt);
            }
        });
        jPanel1.add(dot, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 230, 60, 40));

        div.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        div.setText("/");
        div.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        div.setPreferredSize(new java.awt.Dimension(60, 50));
        div.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                divActionPerformed(evt);
            }
        });
        jPanel1.add(div, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 290, 60, 40));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 294, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 352, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents
    String caltotal;
    int num1;
    int num2;
    int res;
    String option;
   
    private void nineActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nineActionPerformed
        // TODO add your handling code here:
         caltotal=jLabel1.getText();
      jLabel1.setText(caltotal + "9");
    }//GEN-LAST:event_nineActionPerformed

    private void sevenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sevenActionPerformed
        // TODO add your handling code here:
      caltotal=jLabel1.getText();
      jLabel1.setText(caltotal + "7");
    }//GEN-LAST:event_sevenActionPerformed

    private void eightActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eightActionPerformed
        // TODO add your handling code here:
        caltotal=jLabel1.getText();
      jLabel1.setText(caltotal + "8");
    }//GEN-LAST:event_eightActionPerformed

    private void fourActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fourActionPerformed
        // TODO add your handling code here:
         caltotal=jLabel1.getText();
      jLabel1.setText(caltotal + "4");
    }//GEN-LAST:event_fourActionPerformed

    private void fiveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fiveActionPerformed
        // TODO add your handling code here:
         caltotal=jLabel1.getText();
      jLabel1.setText(caltotal + "5");
    }//GEN-LAST:event_fiveActionPerformed

    private void sixActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sixActionPerformed
        // TODO add your handling code here:
         caltotal=jLabel1.getText();
      jLabel1.setText(caltotal + "6");
    }//GEN-LAST:event_sixActionPerformed

    private void oneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_oneActionPerformed
        // TODO add your handling code here:
         caltotal=jLabel1.getText();
      jLabel1.setText(caltotal + "1");
    }//GEN-LAST:event_oneActionPerformed

    private void twoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_twoActionPerformed
        // TODO add your handling code here:
         caltotal=jLabel1.getText();
      jLabel1.setText(caltotal + "2");
    }//GEN-LAST:event_twoActionPerformed

    private void threeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_threeActionPerformed
        // TODO add your handling code here:
         caltotal=jLabel1.getText();
      jLabel1.setText(caltotal + "3");
    }//GEN-LAST:event_threeActionPerformed

    private void twozeroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_twozeroActionPerformed
        // TODO add your handling code here:
         caltotal=jLabel1.getText();
      jLabel1.setText(caltotal + "00");
    }//GEN-LAST:event_twozeroActionPerformed

    private void zeroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_zeroActionPerformed
        // TODO add your handling code here:
         caltotal=jLabel1.getText();
      jLabel1.setText(caltotal + "0");
    }//GEN-LAST:event_zeroActionPerformed

    private void dotActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dotActionPerformed
        // TODO add your handling code here:
         caltotal=jLabel1.getText();
      jLabel1.setText(caltotal + ".");
    }//GEN-LAST:event_dotActionPerformed

    private void addActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addActionPerformed
        // TODO add your handling code here:
        option ="+";
        num1=Integer.parseInt(jLabel1.getText());
        jLabel1.setText("");
             
    }//GEN-LAST:event_addActionPerformed

    private void subActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_subActionPerformed
        // TODO add your handling code here:
         option ="-";
        num1=Integer.parseInt(jLabel1.getText());
        jLabel1.setText("");
    }//GEN-LAST:event_subActionPerformed

    private void mulActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mulActionPerformed
        // TODO add your handling code here:
         option ="*";
        num1=Integer.parseInt(jLabel1.getText());
        jLabel1.setText("");
    }//GEN-LAST:event_mulActionPerformed

    private void divActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_divActionPerformed
        // TODO add your handling code here:
         option ="/";
        num1=Integer.parseInt(jLabel1.getText());
        jLabel1.setText("");
    }//GEN-LAST:event_divActionPerformed
  
    private void equalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_equalActionPerformed
        // TODO add your handling code here:
        num2=Integer.parseInt(jLabel1.getText());
        if(option.equals("+"))
        {
            res = num1+num2;
        }
        if(option.equals("-"))
        {
            res=num1-num2;
        }
        if(option.equals("*"))
        {
            res=num1*num2;
        }
        if(option.equals("/"))
        {
            res=num1/num2;
        }
        jLabel1.setText(res+"");
                
    }//GEN-LAST:event_equalActionPerformed

    private void dallActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dallActionPerformed
        // TODO add your handling code here:
        jLabel1.setText("");
        res=(0);
        num1=(0);
        num2=(0);
    }//GEN-LAST:event_dallActionPerformed

    private void doneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_doneActionPerformed
        // TODO add your handling code here:
        String str=jLabel1.getText();
        jLabel1.setText("");
        for(int i=0;i<str.length()-1;i++)
        {
            jLabel1.setText(jLabel1.getText()+str.charAt(i));
        }
    }//GEN-LAST:event_doneActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CalculatorApp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CalculatorApp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CalculatorApp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CalculatorApp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CalculatorApp().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton add;
    private javax.swing.JButton dall;
    private javax.swing.JButton div;
    private javax.swing.JButton done;
    private javax.swing.JButton dot;
    private javax.swing.JButton eight;
    private javax.swing.JButton equal;
    private javax.swing.JButton five;
    private javax.swing.JButton four;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton mul;
    private javax.swing.JButton nine;
    private javax.swing.JButton one;
    private javax.swing.JButton seven;
    private javax.swing.JButton six;
    private javax.swing.JButton sub;
    private javax.swing.JButton three;
    private javax.swing.JButton two;
    private javax.swing.JButton twozero;
    private javax.swing.JButton zero;
    // End of variables declaration//GEN-END:variables
}
